name: memos-dev

services:
  memos:
    container_name: memos-api-docker
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8005:8005"
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/app/src
      - HF_ENDPOINT=https://hf-mirror.com
      - QDRANT_HOST=qdrant-docker
      - QDRANT_PORT=6333
      - NEO4J_URI=bolt://neo4j-docker:7687
    volumes:
      - ../src:/app/src
      - .:/app/docker
    networks:
      - memos_network


volumes:
  neo4j_data:
  neo4j_logs:

networks:
  memos_network:
    driver: bridge
